### PR TITLE
WIP: Add process type docs

### PR DESCRIPTION
**Pull request by RCheesley**
This PR adds some documentation for the Process Types introduced with [this PR](https://github.com/decidim/decidim/pull/8583) and this [feature request](https://meta.decidim.org/processes/roadmap/f/122/proposals/16850).

- Adds Spaces > Processes > Types page
- Adds screenshots from GitHub issue
- Adds to global navigation

### CODE REVIEW

**Comment by andreslucena** [comment]
Hi @RCheesley, thanks for your contribution!!

With this PR we could detect that actually the build process for local development and for the Nelify preview functionality was broken (reported at #131). Now it should work on both cases. 

FYI, for other reasons (adding Crowdin support) we also moved the directory structure, (moving `en` to `docs/en/`), so you need to merge with `develop` branch and make adjustments accordingly. 

For testing out the preview feature I opened #138 based on this branch, and you can check out how this page looks like at https://deploy-preview-138--decidim-documentation.netlify.app/en/develop/admin/spaces/assemblies/types 

Feel free to retake that branch or check out my changes to see how to fix the deploy preview for this PR.

**Comment by RCheesley** [comment]
@andreslucena might it be easier to just create a new PR given the changes that have happened? I'm not overly confident with dealing with merge conflicts! 🙈

**Comment by andreslucena** [comment]
> @andreslucena might it be easier to just create a new PR given the changes that have happened? I'm not overly confident with dealing with merge conflicts! 

Yeah, they can be tricky to solve. 

I've added you to the @decidim/documentation team so it's easier to work with this repository. You should have an invitation, after you accept it you should be able to retake #138 with the following commands:

``` 
git remote add upstream git@github.com:decidim/documentation.git # this can be https, depending on how you have set up git locally 
git fetch upstream
git checkout upstream/feature/processes-types
git checkout -b feature/processes-types
```

Let me know if that works for you!

**Comment by RCheesley** [comment]
Closing in favour of #138

**Pull request closed without merging**
