### PR TITLE
Remove gender references

### LINKED ISSUE #145: Proposal: Remove gendered references in the docs
Hi folks!

I want to propose making a PR to remove the (many) gender references (he/she/his/hers/him/her etc) and instead replace them with more inclusive gender neutral terms.

This is considered best practice in many documentation and writing style guides, some examples:

Google: https://developers.google.com/style/inclusive-documentation
EU: https://publications.europa.eu/code/en/en-4100600en.htm 
UN: https://www.un.org/en/gender-inclusive-language/guidelines.shtml

I'm happy to work on a PR but it will be large touch a lot of parts of the docs, and therefore might cause some work for translators.

Figured it would make sense to ask if such a PR will be accepted before launching into it!

### PR DESCRIPTION
**Pull request by RCheesley**
Hi folks!

### 👋 Intro
This PR is based on #147 (making it easier to find) and fixes #145 - it removes gendered references which are in the feminine, in favour of using gender-neutral they/them/their. I did not find any in the masculine (he/his/him).

### 🤔 What's it doing?
I've searched for instances of she or her, and replaced with the appropriate gender neutral term. In some cases a small re-write of the sentence is needed for grammatical reasons, and if I spotted an obvious typo at the same place I fixed it.

## 🛟 Considerations
In discussion with @andreslucena I understand Decidim prefers not to use contractions, so where I spotted them as I was working on a sentence, I fixed them (eg from don't to do not) to save fixing them in a later PR - figured it makes sense to fix as I saw them.

It might also be worth adding some guidance to writers to not use those gendered terms going forward.

### CODE REVIEW

**Comment by andreslucena** [comment]
@RCheesley sorry again for the delay with this PR. Can you merge with `develop` branch? I want to have a better diff. 

If  that's too much of a hassle, you can create a new PR with only the relevant changes for this PR (i.e. cherry-picking [fde6579](https://github.com/decidim/documentation/pull/151/commits/fde657960477ccb037ed409eb7e36d6f689b374b) and [6f7caed](https://github.com/decidim/documentation/pull/151/commits/6f7caede3197e00819b89f5f44f9896e2d5b7f7d))

Thanks!

**Comment by RCheesley** [comment]
@andreslucena hopefully just done that!

**Comment by RCheesley** [comment]
@andreslucena anything else I need to do here? Looks like things are failing :(

**Review by andreslucena — APPROVED** [review]
I need to actually allocate time to check out what's happening with the netlify preview. At the moment we can ignore it, as I've checked the PR locally and everything works perfect. Thanks for the PR and sorry for the delay :/

**Comment by andreslucena** [comment]
Merging with the netlify preview integration broken, as it actually compiles. We need to fix that in another PR.

**Pull request merged**
